import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from "@mantine/core";
import { Notifications } from '@mantine/notifications';
import { UserProvider } from "@/components/UserProvider";
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {


  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        <MantineProvider theme={{fontFamily: 'Inter, sans-serif'}}>
          <Notifications position="top-center" zIndex={1200}/>
            <UserProvider>
              {children}
            </UserProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
